board_size: 8

ui:
  background_col: [0.42899999, 0.51700002, 0.69599998] # [r, g, b] float value from 0~1. 
  board_fill_col:
    - 0.311274529
    - 0.366205394
    - 0.622549057
  line_col:
    - 0.539215684
    - 0.769607961
    - 1
  hint_valid_move_col:
    - 0.634902835
    - 0.892156839
    - 0.345492095